# Generated by Django 5.2.14 on 2026-05-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='include_inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='template_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
