# Generated by Django 5.2.14 on 2026-05-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_emaildraft_include_inactive_emaildraft_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='signature_source',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='signature_url',
            field=models.URLField(blank=True),
        ),
    ]
