# Generated by Django 5.2.14 on 2026-05-24 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_webuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='web_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer.webuser'),
        ),
    ]
